os: Visual Studio 2015

build_script:
  - ps: gitversion /output buildserver
  - ps: .\build\Update-Version.ps1 $env:GitVersion_NuGetVersion
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: dotnet --verbose build .\DocumentFormat.OpenXml.Tests

after_build:
  - ps: dotnet --verbose pack .\DocumentFormat.OpenXml -o .

test_script:
  - cmd: dotnet test .\DocumentFormat.OpenXml.Tests
