os: Visual Studio 2015

environment:
  SignClientSecret:
    secure: 2QKIbnEaxM/df01+GLvTjVKdLL7RlwKmCR/APcWFRUUF2VQWBRQFQ1DP3gK49epL

install:
  - ps: nuget install -ExcludeVersion SignClient -Version 0.5.0-beta4 -pre -OutputDirectory .\build\

build_script:
  - ps: gitversion /output buildserver
  - ps: .\build\Update-Version.ps1 $env:GitVersion_NuGetVersion
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: dotnet --verbose build .\DocumentFormat.OpenXml.Tests

after_build:
  - ps: dotnet --verbose pack .\DocumentFormat.OpenXml -o .
  - ps: .\build\SignPackage.ps1

test_script:
  - cmd: dotnet test .\DocumentFormat.OpenXml.Tests

artifacts:
  - path: '*.nupkg'
    name: NuGetArtifacts

deploy:
  provider: NuGet
  server: https://dotnet.myget.org/F/open-xml-sdk/api/v2/package
  api_key:
    secure: rxiGDTFaiouAgVTK2ESDt/RjxVH0sBiomuohk4j4byhZUwxNIXq6RN8oK3/nXDJb
  skip_symbols: false
  symbol_server: https://dotnet.myget.org/F/open-xml-sdk/symbols/api/v2/packages
  artifact: /.*\.nupkg/
  on:
    branch: [master, vNext, Office2016]
